services:
  # Backend API Service
  - type: web
    name: call-analysis-backend
    env: node
    plan: starter
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: https://call-analysis-frontend.onrender.com
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: DATABASE_URL
        fromDatabase:
          name: call-analysis-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: call-analysis-redis
          property: connectionString
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_FROM
        value: noreply@callanalysis.com
      - key: UPLOAD_PATH
        value: ./uploads
      - key: MAX_FILE_SIZE
        value: 10485760
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: LOG_LEVEL
        value: info
      - key: WS_PORT
        value: 10001

  # Frontend Service
  - type: web
    name: call-analysis-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://call-analysis-backend.onrender.com

  # Redis Service
  - type: redis
    name: call-analysis-redis
    plan: starter
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []

databases:
  - name: call-analysis-db
    databaseName: call_analysis_db
    user: call_analysis_user
    plan: starter
